version: '3'
services:
  reearth:
    image: reearth/reearth:nightly
    environment:
      REEARTH_DB: mongodb://reearth-mongo
      # REEARTH_AUTH0_AUDIENCE:
      # REEARTH_AUTH0_CLIENTID:
      # REEARTH_AUTH0_CLIENTSECRET:
      # REEARTH_AUTH0_DOMAIN:
      # REEARTH_AUTH0_WEBCLIENTID:
    ports:
      - 8080:8080
    links:
      - reearth-mongo
    depends_on:
      - reearth-mongo
  reearth-mongo:
    image: mongo:4.2.0-bionic
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
